filter:
    paths: [module/*]
    excluded_paths: [module/*/tests/*]
    
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes: [php]
    php_analyzer:
        enabled: true
        extensions: [php]
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
    sensiolabs_security_checker: true

