language: php
php:
 - 5.4
 - 5.5
 - 5.6

before_script:
 - npm install -g grunt-cli
 - npm install
 - composer install --prefer-source

script:
 - grunt test:ci

after_script:
 - vendor/bin/phpcov merge -n --clover=build/logs/clover.xml build/coverage
 - vendor/bin/coveralls -n
