version: '2'
services:
    application:
        build: ./
        links:
            - mysql
        volumes:
            - data:/var/www/html/data
    mysql:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
    nginx:
        image: nginx:1.10
        depends_on:
            - application
        links:
            - 'application:php-fpm'
        volumes_from:
            - application
    liquibase:
        build: docker/liquibase
        links:
            - mysql
        volumes_from:
            - application
volumes:
    data:
        driver: local
    mysql:
        driver: local
