version: '2'
services:
  application:
    build: ./
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
  nginx:
    image: nginx:1.10
    depends_on:
      - application
    links:
      - 'application:php-fpm'
    volumes_from:
      - application
volumes:
    database:
        driver: local
