<?php echo $this->doctype(); ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Ajasta')->setSeparator(' - ');
        echo $this->headLink()->prependStylesheet($this->basePath('assets/stylesheets/main.css'));
        echo $this->headScript()->prependFile($this->basePath('assets/javascript/main.js'));
        ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   <a class="navbar-brand" href="#">Ajasta</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                    echo $this->navigation('Ajasta\Navigation')
                        ->menu()
                        ->renderMenu(null, [
                            'ulClass' => 'nav navbar-nav',
                            'maxDepth' => 0,
                        ]);
                    ?>
                </div>
            </div>
        </div>

        <div class="container">
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
