<div class="page-header">
    <a href="<?php echo $this->url('clients/create'); ?>" class="btn btn-primary pull-right">
        <span class="glyphicon glyphicon-plus"></span>
        Create new client
    </a>
    <h1>Clients</h1>
</div>

<table id="client-table"  class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Language</th>
            <th>Currency</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->clients as $client): ?>
            <tr>
                <td><?php echo $this->escapeHtml($client->getName()); ?></td>
                <td><?php echo $this->escapeHtml($this->displayLanguage($client->getLocale())); ?></td>
                <td><?php echo $this->escapeHtml($this->displayCurrency($client->getCurrencyCode())); ?></td>
                <td>
                    <a href="<?php echo $this->url('clients/show', ['clientId' => $client->getId()]); ?>">Show</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
$(document).on('ready', function(){
    $('#client-table').DataTable({
        columnDefs: [
            {searchable: true, orderable: true},
            {searchable: true, orderable: true},
            {searchable: true, orderable: true},
            {searchable: false, orderable: false}
        ],
        order: [0, 'asc'],
        stateSave: true
    });
});
</script>
