<div class="page-header">
    <div class="pull-right">
        <a href="<?php echo $this->url('clients/get-archived-clients'); ?>" class="btn btn-default" id="open-archive">
            <span class="glyphicon glyphicon-folder-open"></span>
            Archive
        </a>
        <a href="<?php echo $this->url('clients/create'); ?>" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span>
            Create new client
        </a>
    </div>

    <h1>Clients</h1>
</div>

<table id="client-table"  class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Language</th>
            <th>Currency</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->clients as $client): ?>
            <tr>
                <td><?php echo $this->escapeHtml($client->getName()); ?></td>
                <td><?php echo $this->escapeHtml($this->displayLanguage($client->getLocale())); ?></td>
                <td><?php echo $this->escapeHtml($this->displayCurrency($client->getCurrencyCode())); ?></td>
                <td>
                    <a href="<?php echo $this->url('clients/show', ['clientId' => $client->getId()]); ?>" class="btn btn-default btn-xs">Show</a>
                    <a href="<?php echo $this->url('clients/edit', ['clientId' => $client->getId()]); ?>" class="btn btn-default btn-xs">Edit</a>
                    <a href="<?php echo $this->url('clients/archive', ['clientId' => $client->getId()]); ?>" class="btn btn-default btn-xs">Archive</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
$(document).on('ready', function(){
    $('#client-table').DataTable({
        columnDefs: [
            {searchable: true, orderable: true},
            {searchable: true, orderable: true},
            {searchable: true, orderable: true},
            {searchable: false, orderable: false}
        ],
        order: [0, 'asc'],
        stateSave: true
    });
});
</script>

<div id="archive-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Archive</h4>
            </div>
            <div class="modal-body">
                <table id="archive-table"  class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr data-role="prototype">
                            <td data-role="name"></td>
                            <td>
                                <a data-role="action-activate" class="btn btn-default btn-xs">Activate</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
$('#open-archive').on('click', function(e){
    e.preventDefault();

    $.getJSON($(this).attr('href'), function(data){
        var modal     = $('#archive-modal');
        var tbody     = modal.find('tbody');
        var prototype = tbody.children('tr[data-role="prototype"]');

        tbody.children('tr[data-role!="prototype"]').remove();
        prototype.show();

        $.each(data.clients, function(index, client){
            var tr = prototype.clone();
            tr.removeAttr('data-role');
            tr.find('td[data-role="name"]').text(client.name);
            tr.find('a[data-role="action-activate"]').attr('href', client.activate_url);
            tbody.append(tr);
        });

        prototype.hide();

        $('#archive-table').DataTable({
            columnDefs: [
                {searchable: true, orderable: true},
                {searchable: false, orderable: false}
            ],
            order: [0, 'asc']
        });

        $('#archive-modal').modal().on('hidden.bs.modal', function(){
            $('#archive-table').DataTable().destroy();
        });
    });
});
</script>