<div class="page-header">
    <a href="<?php echo $this->url('invoices/edit', ['invoiceId' => $this->invoice->getId()]); ?>" class="btn btn-primary pull-right">
        <span class="glyphicon glyphicon-pencil"></span>
        Edit invoice
    </a>
    <h1>Invoice: </h1>
</div>

<dl class="dl-horizontal">
    <dt>Language</dt>
    <dd><?php echo $this->escapeHtml($this->displayLanguage($this->invoice->getLocale())); ?></dd>

    <dt>Currency</dt>
    <dd><?php echo $this->escapeHtml($this->displayCurrency($this->invoice->getCurrencyCode())); ?></dd>
</dl>
