<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <title><?php echo $this->escape('title'); ?> - Ajasta</title>
        <?php echo $this->section('head-meta'); ?>
        <link type="text/css" rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.min.css">
        <link type="text/css" rel="stylesheet" href="/css/app.css">
        <?php echo $this->section('head-link'); ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="https://github.com/DASPRiD/Ajasta">
                        <img src="/images/ajasta-logo.svg" alt="Ajasta">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#" class="nav-link">Dashboard</a> <span class="sr-only">(current)</span></li>
                        <li><a href="#" class="nav-link">Invoices</a></li>
                        <li><a href="#" class="nav-link">Clients</a></li>
                        <li><a href="#" class="nav-link">Projects</a></li>
                        <li><a href="#" class="nav-link">Settings</a></li>
                    </ul>

                    <p class="navbar-text navbar-right">
                        <img src="https://www.gravatar.com/avatar/<?php echo md5($user->getEmailAddress()); ?>?s=20&amp;r=g" class="img-rounded">
                        <?php echo $this->escape($user->getUsername()); ?>
                        |
                        <a href="/logout" class="navbar-link">Sign Out</a>
                    </p>
                </div>
            </div>
        </nav>

        <div class="container">
            <?php echo $this->section('content'); ?>
        </div>

        <script type="text/javascript" src="/vendor/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
        <?php echo $this->section('inline_script'); ?>
    </body>
</html>
