<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <title>Ajasta</title>
        <?php echo $this->section('head-meta'); ?>
        <link type="text/css" rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.min.css">
        <link type="text/css" rel="stylesheet" href="/css/login.css">
        <?php echo $this->section('head-link'); ?>
    </head>
    <body>
        <?php echo $this->section('content'); ?>

        <script type="text/javascript" src="/vendor/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
        <?php echo $this->section('inline_script'); ?>
    </body>
</html>
